# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2372b5cdae38c90c6d18f66ababf475786a01b5b0b588571a1288a37b8645b185e7db670de02b042d0d478460268194bb154f6d025f38c89d164d99a2cb10b8e

test:
  secret_key_base: c5566ecd8f27d42f430d86ab02c93323c1a887b7d166f9a96feba931de5af3813d871f0f64d82f48748e299f9b315b2f5c43b904bc724ec96d04ba264e419618

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
